# Generated by Django 5.0.6 on 2024-07-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_testimonial_delete_portfolio_team_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
